# Generated by Django 3.2.8 on 2021-12-10 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualNeeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YearDate', models.DateTimeField()),
                ('checked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(max_length=50)),
                ('Quantity', models.IntegerField(default=0)),
                ('FirstBrand', models.CharField(max_length=50, null=True)),
                ('SecondBrand', models.CharField(max_length=50, null=True)),
                ('ThirdBrand', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestedDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TotalQuantities', models.IntegerField()),
                ('FirstSems', models.IntegerField()),
                ('SecondSems', models.IntegerField()),
                ('ThirdSems', models.IntegerField()),
                ('i', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.items')),
            ],
        ),
        migrations.AddField(
            model_name='items',
            name='tag',
            field=models.ManyToManyField(to='main.Tag'),
        ),
        migrations.CreateModel(
            name='Faculties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FacultiesName', models.CharField(max_length=50)),
                ('an', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.annualneeds')),
            ],
        ),
        migrations.AddField(
            model_name='annualneeds',
            name='i',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.items'),
        ),
    ]
