# Generated by Django 3.2.8 on 2021-12-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='FirstBrand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='SecondBrand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='ThirdBrand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
