# Generated by Django 3.2.8 on 2021-12-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211210_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annualneeds',
            name='i',
        ),
        migrations.AddField(
            model_name='items',
            name='annualneed',
            field=models.ManyToManyField(to='main.AnnualNeeds'),
        ),
    ]
