# Generated by Django 4.0 on 2021-12-14 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211211_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsAll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_Name', models.CharField(max_length=50)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tag')),
            ],
        ),
        migrations.CreateModel(
            name='ItemsOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(blank=True, max_length=150, null=True)),
                ('FirstBrand', models.CharField(blank=True, max_length=50, null=True)),
                ('SecondBrand', models.CharField(blank=True, max_length=50, null=True)),
                ('ThirdBrand', models.CharField(blank=True, max_length=50, null=True)),
                ('FlowRate', models.CharField(blank=True, max_length=100, null=True)),
                ('Unit', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WareHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(default=1)),
                ('Description', models.CharField(blank=True, max_length=150, null=True)),
                ('Brand', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='items',
            name='annualneed',
        ),
        migrations.RemoveField(
            model_name='items',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='annualneeds',
            name='checked',
        ),
        migrations.AddField(
            model_name='annualneeds',
            name='Faculity',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Faculties',
        ),
        migrations.AddField(
            model_name='itemsorder',
            name='WareHouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.warehouse'),
        ),
        migrations.AddField(
            model_name='itemsorder',
            name='annualneed',
            field=models.ManyToManyField(to='main.AnnualNeeds'),
        ),
        migrations.AddField(
            model_name='itemsorder',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.itemsall'),
        ),
        migrations.AlterField(
            model_name='requesteddocs',
            name='i',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.itemsorder'),
        ),
        migrations.DeleteModel(
            name='Items',
        ),
    ]
