# Generated by Django 4.0 on 2021-12-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_itemsall_itemsorder_warehouse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualneeds',
            name='YearDate',
            field=models.DateField(),
        ),
    ]
