# Generated by Django 4.0 on 2021-12-14 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_annualneeds_yeardate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemsorder',
            name='WareHouse',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.itemsall'),
            preserve_default=False,
        ),
    ]
