# Generated by Django 4.0 on 2021-12-14 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_itemsorder_warehouse_warehouse_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requesteddocs',
            old_name='i',
            new_name='item',
        ),
    ]
