# Generated by Django 4.0 on 2021-12-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_requesteddocs_totalquantities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tagname',
            field=models.CharField(choices=[('General', 'General'), ('Medical', 'Medical'), ('IT', 'IT'), ('Engineering', 'Engineering')], max_length=200, null=True),
        ),
    ]
