# Generated by Django 4.0 on 2021-12-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_itemsorder_approxprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsorder',
            name='FirstSems',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itemsorder',
            name='SecondSems',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itemsorder',
            name='ThirdSems',
            field=models.IntegerField(default=0),
        ),
    ]
