# Generated by Django 4.0 on 2021-12-19 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0019_itemsorder_firstsems_itemsorder_secondsems_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=200)),
                ('Faculity', models.CharField(choices=[('IT', 'IT'), ('ARCHITECTURE', 'ARCHITECTURE'), ('MEDICINE', 'MEDICINE'), ('PHARMACY', 'PHARMACY'), ('DENTISTRY', 'DENTISTRY'), ('BUSINESS', 'BUSINESS')], max_length=200, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
            ],
        ),
        migrations.DeleteModel(
            name='RequestedDocs',
        ),
        migrations.AddField(
            model_name='annualneeds',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.users'),
        ),
    ]
