# Generated by Django 4.0 on 2021-12-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_annualneeds_complete_remove_itemsorder_annualneed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsorder',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
