# Generated by Django 4.0 on 2021-12-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_itemsorder_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Faculity',
            field=models.CharField(blank=True, choices=[('IT', 'IT'), ('ARCHITECTURE', 'ARCHITECTURE'), ('MEDICINE', 'MEDICINE'), ('PHARMACY', 'PHARMACY'), ('DENTISTRY', 'DENTISTRY'), ('BUSINESS', 'BUSINESS')], max_length=200, null=True),
        ),
    ]
