# Generated by Django 3.2.7 on 2022-01-04 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0023_alter_users_faculity'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YearDate', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Being Reviewed', 'Being Reviewed'), ('Needs Alteration', 'Needs Alteration'), ('Approved', 'Approved')], default='Pending', max_length=200, null=True)),
                ('complete', models.BooleanField(default=False)),
                ('RequestingParty', models.CharField(choices=[('IT', 'IT'), ('ARCHITECTURE', 'ARCHITECTURE'), ('MEDICINE', 'MEDICINE'), ('PHARMACY', 'PHARMACY'), ('DENTISTRY', 'DENTISTRY'), ('BUSINESS', 'BUSINESS')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(max_length=50)),
                ('Quantity', models.IntegerField(default=1)),
                ('Description', models.CharField(blank=True, max_length=150, null=True)),
                ('Brand', models.CharField(blank=True, max_length=50, null=True)),
                ('tagname', models.CharField(choices=[('General', 'General'), ('Medical', 'Medical'), ('IT', 'IT'), ('Engineering', 'Engineering')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstSemsQuantity', models.IntegerField(default=0)),
                ('SecondSemsQuantity', models.IntegerField(default=0)),
                ('ThirdSemsQuantity', models.IntegerField(default=0)),
                ('Total', models.IntegerField(default=0)),
                ('Description', models.CharField(blank=True, max_length=150, null=True)),
                ('FirstBrand', models.CharField(blank=True, max_length=50, null=True)),
                ('SecondBrand', models.CharField(blank=True, max_length=50, null=True)),
                ('ThirdBrand', models.CharField(blank=True, max_length=50, null=True)),
                ('FlowRate', models.CharField(blank=True, max_length=100, null=True)),
                ('Unit', models.CharField(blank=True, max_length=100, null=True)),
                ('ApproxPrice', models.FloatField(default=0)),
                ('annualneed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.annualneed')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.item')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StockName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=200)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='itemsorder',
            name='annualneed',
        ),
        migrations.RemoveField(
            model_name='itemsorder',
            name='item',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='item',
        ),
        migrations.DeleteModel(
            name='AnnualNeeds',
        ),
        migrations.DeleteModel(
            name='ItemsAll',
        ),
        migrations.DeleteModel(
            name='ItemsOrder',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.DeleteModel(
            name='WareHouse',
        ),
        migrations.AddField(
            model_name='item',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.stock'),
        ),
        migrations.AddField(
            model_name='annualneed',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.user'),
        ),
    ]
