# Generated by Django 4.0 on 2022-01-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20220104_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='FirstSemsQuantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='SecondSemsQuantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='ThirdSemsQuantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='Total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
