# Generated by Django 4.0 on 2022-01-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_item_quantity_alter_order_firstsemsquantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='RequestingParty',
            field=models.CharField(choices=[('IT', 'IT'), ('ARCHITECTURE', 'ARCHITECTURE'), ('MEDICINE', 'MEDICINE'), ('PHARMACY', 'PHARMACY'), ('DENTISTRY', 'DENTISTRY'), ('BUSINESS', 'BUSINESS')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='annualneed',
            name='RequestingParty',
            field=models.CharField(blank=True, choices=[('IT', 'IT'), ('ARCHITECTURE', 'ARCHITECTURE'), ('MEDICINE', 'MEDICINE'), ('PHARMACY', 'PHARMACY'), ('DENTISTRY', 'DENTISTRY'), ('BUSINESS', 'BUSINESS')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Email',
            field=models.CharField(max_length=100),
        ),
    ]
