# Generated by Django 4.0 on 2022-01-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_user_requestingparty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Total',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
