# Generated by Django 4.0 on 2022-01-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='FirstSemsQuantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='SecondSemsQuantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='ThirdSemsQuantity',
            field=models.PositiveIntegerField(),
        ),
    ]
