# Generated by Django 4.0 on 2022-01-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_order_firstsemsquantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ApproxPrice',
            field=models.FloatField(),
        ),
    ]
